"""Initial migration

Revision ID: 2f4085bab2ea
Revises: 
Create Date: 2025-04-05 01:26:29.071375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f4085bab2ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boxes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('top', sa.Integer(), nullable=True),
    sa.Column('left', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boxes')
    # ### end Alembic commands ###
