"""Add room_id to Box

Revision ID: cc3358cc70ee
Revises: 2f4085bab2ea
Create Date: 2025-04-12 01:13:47.903212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc3358cc70ee'
down_revision = '2f4085bab2ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boxes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'rooms', ['room_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boxes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('room_id')

    # ### end Alembic commands ###
